[workspace]
members = [
    "decent",
    "decent-macros",
]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies.decent]
version = "0.1.0"
path = "decent"

[workspace.dependencies.decent-macros]
version = "0.1.3"
path = "decent-macros"
