[package]
name = "decent"
version = "0.2.1"
edition = "2024"

[dependencies]
fixed = { version = "1.29.0", optional = true }
num = "0.4.3"

[features]
default = ["platform_dependent"]
platform_dependent = []
fixed = ["dep:fixed"]
