[package]
name = "decent-macros"
version = "0.1.3"
edition = "2024"

[dependencies]
decent = { workspace = true }
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.104", features = ["full"] }

[lib]
proc-macro = true
